name = "RecursiveDicts"
uuid = "e20b0d26-85b9-4cc4-ab0c-abba12ca33a5"
authors = ["Sam Atman <atmanistan@gmail.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.6"
Test = "1"
Random = "1"
Aqua = "0.1.0 - 0.9.0"

[extras]
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"

[targets]
test = ["Aqua", "Test", "Random"]
